In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
df=pd.read_csv('cardekho_imputated.csv')

In [6]:
df.head()

,carNumber,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [9]:
df=df.drop('carNumber',axis=1)
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [10]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [11]:
df['car_name'].value_counts()

car_name
Hyundai i20              906
Maruti Swift Dzire       890
Maruti Swift             781
Maruti Alto              778
Honda City               757
                        ...
Mercedes-AMG C             1
Rolls-Royce Ghost          1
Maserati Quattroporte      1
Isuzu MUX                  1
Force Gurkha               1
Name: count, Length: 121, dtype: int64

In [14]:
df['brand'].value_counts()

brand
Maruti           4992
Hyundai          2982
Honda            1485
Mahindra         1011
Toyota            793
Ford              790
Volkswagen        620
Renault           536
BMW               439
Tata              430
Mercedes-Benz     337
Skoda             334
Audi              192
Datsun            170
Jaguar             59
Land Rover         51
Jeep               41
Kia                32
Porsche            21
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
Maserati            2
ISUZU               2
Ferrari             1
Mercedes-AMG        1
Rolls-Royce         1
Force               1
Name: count, dtype: int64

In [13]:
df['seller_type'].value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [15]:
df['transmission_type'].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [19]:
df=df.drop(columns={'car_name','brand'})

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  str
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  str
 4   fuel_type          15411 non-null  str
 5   transmission_type  15411 non-null  str
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), str(4)
memory usage: 1.3 MB

In [22]:
df['model'].unique()

<StringArray>
[        'Alto',        'Grand',          'i20',     'Ecosport',
      'Wagon R',          'i10',        'Venue',        'Swift',
        'Verna',       'Duster',
 ...
     'Panamera',      'Alturas',       'Altroz',           'NX',
     'Carnival',            'C',           'RX',        'Ghost',
 'Quattroporte',       'Gurkha']
Length: 120, dtype: str

In [23]:
num_features=[feature for feature in df.columns if df[feature].dtype != 'string']
print('numerical features:',len(num_features))
cat_features=[feature for feature in df.columns if df[feature].dtype == 'string']
print('categorical features:',len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<25]
print('discrete features:',len(discrete_features))
continuous_features=[feature for feature in num_features if len(df[feature].unique())>=25]
print('continuous features:',len(continuous_features))

numerical features: 7
categorical features: 4
discrete features: 2
continuous features: 5

In [26]:
## independent and dependent features
from sklearn.model_selection import train_test_split
x=df.drop('selling_price',axis=1)
y=df['selling_price']

In [27]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [28]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
15406     250000
15407     925000
15408     425000
15409    1225000
15410    1200000
Name: selling_price, Length: 15411, dtype: int64

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['model']=le.fit_transform(x['model'])

In [32]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [ ]:
df['seller_type'].unique(),df['fuel_type'].unique()

(<StringArray>
 ['Individual', 'Dealer', 'Trustmark Dealer']
 Length: 3, dtype: str,
 <StringArray>
 ['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric']
 Length: 5, dtype: str)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

num_features=x.select_dtypes(exclude='string').columns
onehot_columns=['seller_type','fuel_type','transmission_type']

preprocessor=ColumnTransformer(
    [
   ("OneHotEncoder",OneHotEncoder(drop='first'),onehot_columns),
   ("StandardScaler",StandardScaler(),num_features)
    ],remainder='passthrough'
)

In [40]:
x=preprocessor.fit_transform(x)

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [42]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [44]:
### model training and model selection

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [50]:
## create a function to Evaluate model 
def evaluate_model(true,predicted):
    mse=mean_squared_error(true,predicted)
    mae=mean_absolute_error(true,predicted)
    rmse=np.sqrt(mse)
    r2score=r2_score(true,predicted)
    return mae,rmse,r2score

In [ ]:
## Beginning model training 
models={
    "LinearRegression": LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeRegressor(),
    "Random Forest Regressor":RandomForestRegressor()
}

In [52]:
from sklearn.metrics import accuracy_score, classification_report,ConfusionMatrixDisplay, \
                            precision_score, recall_score, f1_score, roc_auc_score,roc_curve 
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    

    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_train,y_train_pred)

    print(list(models.keys())[i])

    print('Model performance for Test set')
    print('- r2_score: {:.4f}'.format(model_train_r2))
    print('- mean absolute error: {:.4f}'.format(model_test_mae))
    print('- rmse: {:.4f}'.format(model_train_rmse))

LinearRegression
Model performance for Test set
- r2_score: 0.6218
- mean absolute error: 268101.6071
- rmse: 553855.6665
Lasso
Model performance for Test set
- r2_score: 0.6218
- mean absolute error: 268099.2226
- rmse: 553855.6710
Ridge
Model performance for Test set
- r2_score: 0.6218
- mean absolute error: 268059.8015
- rmse: 553856.3160
K-Neighbors Regressor
Model performance for Test set
- r2_score: 0.8691
- mean absolute error: 91425.6327
- rmse: 325873.0267
Decision Tree
Model performance for Test set
- r2_score: 0.9995
- mean absolute error: 5164.8199
- rmse: 20797.2352
Random Forest Regressor
Model performance for Test set
- r2_score: 0.9755
- mean absolute error: 40043.4762
- rmse: 140893.6743

In [61]:
y_test_pred

array([256759.24534939, 648930.94913986, 627104.64857447, ...,
       789390.81981249, 409711.13174571, 898580.10237753], shape=(3083,))

In [54]:
### initialize few parameter for hyperparameter tuning
knn_params={"n_neighbors":[2,3,10,20,40,50]}
rf_params={"max_depth":[5,8,15,None,10],
           "max_features":[5,7,15,None,10],
           "min_samples_split":[2,8,15,20],
           "n_estimators":[100,200,500,1000]
           }

In [56]:
randomcv_models=[
    ('KNN',KNeighborsRegressor(),knn_params),
    ("RF",RandomForestRegressor(),rf_params)
]

In [58]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}

for name,model,params in randomcv_models:
    random=RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=100,cv=3,verbose=2,n_jobs=-1)
    random.fit(x_train,y_train)
    model_param[name]=random.best_params_

for model_name in model_param:
    print(f"------best params for {model_name}")
    print(model_param[model_name])

c:\Users\preet\anaconda3\envs\practise_env\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=100. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
------best params for KNN
{'n_neighbors': 10}
------best params for RF
{'n_estimators': 200, 'min_samples_split': 2, 'max_features': 5, 'max_depth': 15}

In [60]:
models={
    "K-Neighbors Regressor":KNeighborsRegressor(n_neighbors=10),
    "Random Forest Regressor":RandomForestRegressor(n_estimators=200,min_samples_split=2,max_features=5,max_depth=15)
}


for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    

    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_train,y_train_pred)

    print(list(models.keys())[i])

    print('Model performance for Test set')
    print('- r2_score: {:.4f}'.format(model_train_r2))
    print('- mean absolute error: {:.4f}'.format(model_test_mae))
    print('- rmse: {:.4f}'.format(model_train_rmse))

K-Neighbors Regressor
Model performance for Test set
- r2_score: 0.8371
- mean absolute error: 103471.6175
- rmse: 363460.7006
Random Forest Regressor
Model performance for Test set
- r2_score: 0.9743
- mean absolute error: 56525.3431
- rmse: 144408.7584